// Used to receive data from client during CRUD, contains fields that the client is allowed to send
package nl.carsforyou.garage.dtos.appointment;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class AppointmentRequestDto {
    //appointmentId is generated by database

    @NotNull
    private LocalDateTime appointmentDate;
    @NotNull
    private  String reasonForVisit;

    private  LocalDateTime completedDate;

    @NotNull
    private  Long vehicleId;

    private Long userId;


    public LocalDateTime getAppointmentDate() {
        return appointmentDate;
    }

    public void setAppointmentDate(LocalDateTime appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    public String getReasonForVisit() {
        return reasonForVisit;
    }

    public void setReasonForVisit(String reasonForVisit) {
        this.reasonForVisit = reasonForVisit;
    }

    public LocalDateTime getCompletedDate() {
        return completedDate;
    }

    public void setCompletedDate(LocalDateTime completedDate) {
        this.completedDate = completedDate;
    }

    public Long getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    public Long getCreatedByUserId() {
        return userId;
    }

    public void setCreatedByUserId(Long createdByUserId) {
        this.userId = createdByUserId;
    }
}
