// Used to receive data from client during CRUD, contains fields that the client is allowed to send
package nl.carsforyou.garage.dtos.ServiceOrder;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class ServiceOrderRequestDto {
    //serviceOrderId is generated by database

    @NotNull
    private Long vehicleId;

    private LocalDateTime serviceCompletedDate;         // nullable because service may not be completed yet


    public Long getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    public LocalDateTime getServiceCompletedDate() {
        return serviceCompletedDate;
    }

    public void setServiceCompletedDate(LocalDateTime serviceCompletedDate) {
        this.serviceCompletedDate = serviceCompletedDate;
    }
}
