// Used to receive data from client during CRUD, contains fields that the client is allowed to send
package nl.carsforyou.garage.dtos.customer;

import jakarta.validation.constraints.NotNull;

public class CustomerUploadRequestDto {
    //uploadId generated by database
    //filePath will be decided by server
    //uploadDate will be set by server

    @NotNull
    private Long customerId;

    private String fileType;
    private String fileName;  //file, PNG, PDF, etc  will be saved on the server, not in database

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
