spring.application.name=garage

# Define variables
POSTGRESQL_DATABASENAME = carsforyou
POSTGRESQL_USERNAME = postgres
POSTGRESQL_PASSWORD = password

# Define database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

#Define JPA settings, enable logging yes or no
spring.jpa.show-sql=true

#Force to generate data schema on startup of application
spring.jpa.generate-ddl=true
# create the tables, alternative is update on startup
spring.jpa.hibernate.ddl-auto=create

#database init with a data.sql file after hibernate
spring.sql.init.mode=always
#Whether to defer DataSource initialization until after any EntityManagerFactory beans have been created and initialized.
spring.jpa.defer-datasource-initialization=true
#Additional native properties to set on the JPA provider.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#set customer Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

#make sure to display messages to prevent hiding them by default JSON
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

#sort the endpoints so it enhances the readability
springdoc.swagger-ui.tagsSorter=alpha
#sort the endpoints in Swagger GET > POST > PUT > DELETE
springdoc.swagger-ui.operationsSorter=method

#configure wwhere to store the uploaded files via the CustomerUploadService
garage.upload-dir=C:/temp

#security configuration
# Keycloak issuer
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/Garage
#
## Required by your SecurityConfigOauth2
#spring.security.oauth2.resourceserver.jwt.audiences=account
#client-id=Garage

client-id=Garage
client-secret=GWv4CAZsFO35inn3Cu63F5ZqyjcKFtM9

issuer-uri=http://localhost:9090/realms/${client-id}
audience=account

spring.security.oauth2.resourceserver.jwt.issuer-uri=${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences=${audience}



# Swagger UI OAuth2 login (Authorization Code + PKCE)
springdoc.swagger-ui.oauth.client-id=Garage-Swagger
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid,profile,email