// Used to receive data from client during CRUD, contains fields that the client is allowed to send
package nl.carsforyou.garage.dtos.part;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;

import java.math.BigDecimal;

public class PartsRequestDto {
    //partId is generated by database

    @NotNull
    private String itemNumber;

    @NotNull
    private String itemDescription;

    @PositiveOrZero             //negative qty not allowed and don't make sense
    private int qtyOnHand;
    @PositiveOrZero
    private int qtyOnOrder;

    @NotNull
    private BigDecimal unitCost;

    @NotNull
    private BigDecimal unitPrice;


    public String getItemNumber() {
        return itemNumber;
    }

    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;
    }

    public String getItemDescription() {
        return itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public int getQtyOnHand() {
        return qtyOnHand;
    }

    public void setQtyOnHand(int qtyOnHand) {
        this.qtyOnHand = qtyOnHand;
    }

    public int getQtyOnOrder() {
        return qtyOnOrder;
    }

    public void setQtyOnOrder(int qtyOnOrder) {
        this.qtyOnOrder = qtyOnOrder;
    }

    public BigDecimal getUnitCost() {
        return unitCost;
    }

    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
}
